freebsd_task:
  only_if: $CIRRUS_BRANCH == 'master'
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  freebsd_instance:
    image_family: freebsd-12-1
    cpu: 1
    memory: 2G
  test_script:
    - pkg install -y git cmake
    - mkdir build && cd build
    - cmake -DSANITIZER=address .. && make -j && make check && rm -rf *
    - cmake -DSANITIZER=undefined .. && make -j && make check && rm -rf *