name: armv6
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  archs:
    # The host should always be linux
    runs-on: ubuntu-18.04
    name: Build on armv6
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifact
        id: build
        with:
          arch: armv6
          distro: alpine_latest

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # The shell to run commands with in the container
          shell: /bin/sh

          # Produce a binary artifact and place it in the mounted volume
          run: |
            apk update
            apk add git build-base gcc make valgrind cmake
            mkdir build && cd build
            cmake ..  -DSC_USE_WRAP=OFF && make -j && make check
